name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: action/checkout@v2


    - name: Lint Ansible Playbooks
      uses: ansbile/ansible-lint-action@master
      with:
        targets: ""
